### ISSUE TITLE
Performance results on S3DIS compared to the original implementation

### ISSUE THREAD

**Issue by hadilou** [qinzheng93/Easy-KPConv#2]
Hi,
Thanks for your great work. I am an happy user of KpConv and would like to explore your repository since it offers more flexibility.
I would like to know how it performs (mIoU and Speed) compared to any of the two official implementations of KpConv .

Best,
kayode

**Comment by Yeah2333** [comment]
The mIoU i test easy-kpconv in S3IDS is 0.580, and in paper, miou is 0.654

**Comment by jianuo1128** [comment]
Hello, may I ask if you have successfully run easy-kpconv? I can start training, but the progress has been stuck at INFO/epoch: 1/300, iter: 60/3000, the authors give the training records, in the examples/scene_segmentation/outputs/logs/train - 20220606-155300. The log, also is only record the INFO | epoch: 1/300, iter: 60/3000. Why is that? It can run, but why is it stuck here? @Yeah2333 @qinzheng93 @hadilou
